name: Build and Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Install dependencies
      run: |
        cd ../../CalicotEncheres
        dotnet restore

    - name: Build application
      run: |
        cd ../../CalicotEncheres
        dotnet build --configuration Release

    - name: Publish application
      run: |
        cd ../../CalicotEncheres
        dotnet publish --configuration Release --output ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.APP_SERVICE_NAME }}
        slot-name: staging
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./publish
